"""initial_schema

Revision ID: 5b202a755999
Revises: ecdaffeb00eb
Create Date: 2026-09-14 07:56:11.146390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b202a755999'
down_revision: Union[str, Sequence[str], None] = 'ecdaffeb00eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_category_id'), table_name='categories')
    op.drop_index(op.f('ix_favourites_favorite_id'), table_name='favourites')
    op.drop_index(op.f('ix_ingredients_ingredient_id'), table_name='ingredients')
    op.drop_index(op.f('ix_recipes_recipe_id'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_servings'), table_name='recipes')
    op.create_index(op.f('ix_recipes_servings'), 'recipes', ['servings'], unique=False)
    op.create_index(op.f('ix_recipes_cuisine'), 'recipes', ['cuisine'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipes_cuisine'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_servings'), table_name='recipes')
    op.create_index(op.f('ix_recipes_servings'), 'recipes', ['servings'], unique=True)
    op.create_index(op.f('ix_recipes_recipe_id'), 'recipes', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_ingredients_ingredient_id'), 'ingredients', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_favourites_favorite_id'), 'favourites', ['favourite_id'], unique=False)
    op.create_index(op.f('ix_categories_category_id'), 'categories', ['category_id'], unique=False)
    # ### end Alembic commands ###
