"""add instructions to recipes

Revision ID: cb7cd9430554
Revises: 3722caff0a43
Create Date: 2026-09-12 15:24:49.213667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb7cd9430554'
down_revision: Union[str, Sequence[str], None] = '3722caff0a43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('instructions', sa.Text(), nullable=False))
    op.add_column('recipes', sa.Column('cuisine', sa.String(), nullable=True))
    op.drop_index(op.f('ix_recipes_cousine'), table_name='recipes')
    op.create_index(op.f('ix_recipes_cuisine'), 'recipes', ['cuisine'], unique=True)
    op.drop_column('recipes', 'cousine')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('cousine', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_recipes_cuisine'), table_name='recipes')
    op.create_index(op.f('ix_recipes_cousine'), 'recipes', ['cousine'], unique=True)
    op.drop_column('recipes', 'cuisine')
    op.drop_column('recipes', 'instructions')
    # ### end Alembic commands ###
